##############################
# Author: Stefanos Pleros    #	
# A.M: csd3593               #
#                            #
# ---------------------------#
# File Name: Makefile	     #
# 			     #
##############################


all: cs345sh

cs345sh: cs345sh.c
	gcc -ansi -pedantic -Wall -lreadline -o cs345sh cs345sh.c

clean:
	rm cs345sh

